# -*- coding: utf-8 -*-
"""analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n8eH3hDRCWt4jCciVsFppBD9G-k8Wftj
"""

"""
Hiring Trends & Talent Demand Analytics Project
GitHub-Ready Python Script
------------------------------------------------
This script collects, cleans, analyzes, and visualizes job posting data
related to hiring trends and skills demand.

NOTE: For scraping, replace the placeholder dataset or hook into an API like SerpAPI.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from collections import Counter
import seaborn as sns

# ------------------------------
# 1. LOAD / IMPORT DATA
# ------------------------------
# Replace with real scraped data or CSV
# Sample structure: job_title, company, location, description, skills, date_posted

df = pd.read_excel(r"C:\Users\Jabez pendyala\Downloads\Hiring-Trends-Analytics\data\job_postings_sample.xlsx")




# Preview
df.head()

# ------------------------------
# 2. CLEANING & PREPROCESSING
# ------------------------------
# Drop duplicates and missing values
df.drop_duplicates(inplace=True)
df.dropna(subset=['job_title', 'description'], inplace=True)

# Standardize text fields
df['job_title'] = df['job_title'].str.lower()
df['description'] = df['description'].str.lower()

# ------------------------------
# 3. SKILL EXTRACTION
# ------------------------------
skill_keywords = [
    'python', 'sql', 'excel', 'machine learning', 'data analysis', 'tableau',
    'power bi', 'deep learning', 'statistics', 'communication', 'r', 'aws',
    'tensorflow', 'pandas', 'numpy', 'visualization', 'presentation'
]

# Count skills in job descriptions
skill_counts = {}
for skill in skill_keywords:
    skill_counts[skill] = df['description'].str.contains(skill, case=False).sum()

skill_df = pd.DataFrame({
    'skill': list(skill_counts.keys()),
    'count': list(skill_counts.values())
}).sort_values('count', ascending=False)

# ------------------------------
# 4. JOB TITLE FREQUENCY
# ------------------------------
job_counts = df['job_title'].value_counts().reset_index()
job_counts.columns = ['job_title', 'count']

# ------------------------------
# 5. VISUALIZATION
# ------------------------------
plt.figure(figsize=(10,6))
plt.bar(skill_df['skill'], skill_df['count'])
plt.title('Most Requested Skills in Job Postings')
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig('skills_demand.png')
plt.close()

plt.figure(figsize=(10,6))
plt.bar(job_counts['job_title'].head(10), job_counts['count'].head(10))
plt.title('Top 10 Job Titles Posted')
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig('top_job_titles.png')
plt.close()

# ------------------------------
# 6. SUMMARY OUTPUT
# ------------------------------
print("===== SUMMARY INSIGHTS =====")
print("Top 5 Skills:")
print(skill_df.head())
print("\nMost Common Job Titles:")
print(job_counts.head())

# Save cleaned dataset for GitHub

df.to_csv('cleaned_job_postings.csv', index=False)